### PR TITLE
Feature/more steps

### PR DESCRIPTION
**Pull request by lapistano**
* [x] credentials node in config contains non credential stuff (ie. the domain thing that is part of the app being pushed)
* [x] services-less push, services in config.yml needs to be taken into account during push
* [x] on initial deploy the following line of output should be cleaned up: ``Determining which application slice to be deployedTrying to find deployment slice (green)Initial Deploy, remember to set up the DB``
* [x] On initial deploy removal of oldSlice should only be informational (``Unable to cleanUp old instances: FAILED App test-1-green not found``
* [x] Test business logic to validate it's correct behavior.
* [x] credentials node in config contains non credential stuff (ie. the domain thing that is part of the app being pushed)
* [x] services-less push, services in config.yml needs to be taken into account during push
* [x] on initial deploy the following line of output should be cleaned up: ``Determining which application slice to be deployedTrying to find deployment slice (green)Initial Deploy, remember to set up the DB``
* [x] On initial deploy removal of oldSlice should only be informational (``Unable to cleanUp old instances: FAILED App test-1-green not found``
* [x] cf push output is missing (even with -vvv) though it should be continually streamed to output from the process
* [x] master/develop/unstable handling like in the shell script 
* [x] decouple route name from app name (ie. app is customer-api-blah-blah and router is customer_api)

### Considered stuff:
* [ ] multi-push as described in the issue
* [ ] Add a simple example to the repo (ie. src/Tests/web/app.php and .bp-config.json)
* [ ] automate said example through jenkins...

### Feature Requests to be addressed as GH-Issues
* [ ] make services work with less constraints (ie. i want to add a named rabbitmq instance...)
* [ ] make things overridable on the cli without going through install time config (mostly domain, space, org)

### CODE REVIEW

**Comment by hairmare** [comment]
OK, so this PR request now reflects what you want to merge...  Sadly I still have way too much issues to just be happy with it now :(

For starters I'm absolutely unhappy with how there do not seem to be any unit-tests that test the actual business logic that this PR should be implementing. How come the changes in 4b41ea6da5f67ca2a348054e64c639413f893ad5 do not pertain to testing the actual deploy but fix one of the biggest business logic issues is so far is completely beyond my grasp. This contributes to the fact  that I can't seem to come to an end when reviewing this.

So far here are the issues that I have accumulated. They are in no specific order, but at least some of them are somewhat deal-breakers. Could you please look them through and tell me which of them you want as separate issues and what you think about the others.

* [ ] default and validation for empty cf.credentials.domain (ie. ``'  '`` should not fail)
* [ ] credentials node in config contains non credential stuff (ie. the domain thing that is part of the app being pushed)
* [ ] cf push output is missing (even with -vvv) though it should be continually streamed to output from the process
* [ ] services-less push, services in config.yml needs to be taken into account during push
* [ ] make services work with less constraints (ie. i want to add a named rabbitmq instance...)
* [ ] automatic logout should be deactivatable for dev
* [ ] on initial deploy the following line of output should be cleaned up: ``Determining which application slice to be deployedTrying to find deployment slice (green)Initial Deploy, remember to set up the DB``
* [ ] On initial deploy removal of oldSlice should only be informational (``Unable to cleanUp old instances: FAILED App test-1-green not found``
* [ ]  command ``bin/deploy graviton:deployment:cf:c`` should do something that cannot be done with ``cf app`` or be removed...
* [ ] ``AbstractStep::getCommand`` should be template based
* [ ] Add a simple example to the repo (ie. src/Tests/web/app.php and .bp-config.json)
* [ ] automate said example through jenkins...
* [ ] make things overridable on the cli without going through install time config (mostly domain, space, org)
* [ ] decouple route name from app name (ie. app is customer-api-blah-blah and router is customer_api)
* [ ] master/develop/unstable handling like in the shell script 
* [ ] multi-push as described in the issue

Please also re-read and keep in mind my comments in #3. I Still feel that what has been done here is rather crufty and possibly very over-engineered for the task at hand. Honestly, without resolving the top-heaviness-issue that resulted from implementing the workflow-engine-antipattern in the step thing, I don't feel like I'd be willing to let this deploy my code.

**Comment by lapistano** [comment]
### Fixed stuff:
* [x] Test business logic to validate it's correct behavior.
* [x] credentials node in config contains non credential stuff (ie. the domain thing that is part of the app being pushed)
* [x] services-less push, services in config.yml needs to be taken into account during push
* [x] on initial deploy the following line of output should be cleaned up: ``Determining which application slice to be deployedTrying to find deployment slice (green)Initial Deploy, remember to set up the DB``
* [x] On initial deploy removal of oldSlice should only be informational (``Unable to cleanUp old instances: FAILED App test-1-green not found``

### Considered stuff:
* [ ] master/develop/unstable handling like in the shell script 
* [ ] multi-push as described in the issue
* [ ] Add a simple example to the repo (ie. src/Tests/web/app.php and .bp-config.json)
* [ ] automate said example through jenkins...

### Feature Requests to be addressed as GH-Issues
* [ ] make services work with less constraints (ie. i want to add a named rabbitmq instance...)
* [ ] make things overridable on the cli without going through install time config (mostly domain, space, org)

###  Not understood stuff:
* [ ] cf push output is missing (even with -vvv) though it should be continually streamed to output from the process
    » the 'graviton:deployment:cf:deploy' command does print the output as to the console as soon 
       the Symfony process component does provide it. UNfortunately this is not a constant stream.
* [ ] ``AbstractStep::getCommand`` should be template based
    » pls be more precise, What does 'template based' mean?
* [ ] decouple route name from app name (ie. app is customer-api-blah-blah and router is customer_api)

### Won't fixes
* [ ] default and validation for empty cf.credentials.domain (ie. ``'  '`` should not fail) 
      » the Symfony TreeBuilder of the Configuration Component is currently not able to validate
         that a scalar node is not blank (contains not only whitespaces).
         There is an example in the config.yml.dist, so on could see what to add there. If it is left blank
         I guess it is totally the consumers fault.  
* [ ] automatic logout should be deactivatable for dev
      » in what situation should this be used? I see it as quite dangerous to let a session active when 
         the process is done. 
* [ ]  command ``bin/deploy graviton:deployment:cf:c`` should do something that cannot be done with ``cf app`` or be removed...
       » actually I don't care if this command will be survive or not, but why not keeping it since it is
          already there?

**Comment by hairmare** [comment]
## not understood

* [ ] cf push output :point_right: I need to see what is happening during the push so I can log it.
* [ ] decouple route :point_right: app-name = graviton-master, route = graviton
* [ ] unstable feature :point_right: used for when a dev pushes manually with out the push coming from jenkins. I want this to be the default action unless jenkins is pushing

## Won't fixes
* [ ] deactivate automatic logout :point_right: This breaks my workflow like hell on dev. I you won't implement it you'll have to accept my pr that does
* [ ] remoce checkApp :point_right: Pointless features lead to more complexity without adding any value and need to either gain value or be removed early

**Comment by lapistano** [comment]
About: 
*remoce checkApp :point_right: Pointless features lead to more complexity without adding any value and need to either gain value or be removed early*

Neither pointless, nor is it adding complexity to the deployment process since it is a total separate command. 
Actually this command helped a lot in understanding the way how the Process component does handle the escaping of arguments and shell commands. 
This command actually has the same value as the DeployCommand. The fact that you are not using it does not make it useless or worthless. 
Pls stop making such pointless assumptions and futher stop insulting people only because they do not agree with you opinion.

**Comment by hairmare** [comment]
k, sorry

**Comment by lapistano** [comment]
The next push does implement:
[x] deactivate automatic logout :point_right: This breaks my workflow like hell on dev. I you won't implement it you'll have to accept my pr that does
 » use `--no-logout` option to achieve this (tried to add `-nl` as shortcut, but it was not accepted. If a shortcut is to be introduced, pls open a GH issue).

[x] cf push output :point_right: I need to see what is happening during the push so I can log it.
   » Now the status msgs of a deployment will directly streamed to stdout. There currently is no option to deactive it, if this is necessary pls open a GH Issue.

[x] unstable feature :point_right: used for when a dev pushes manually with out the push coming from jenkins. I want this to be the default action unless jenkins is pushing
  » use the 2nd optional argument to change the identifier.
``` ./bin/deploy graviton:deployment:cf:deploy graviton ``` 
will result in:
AppName: graviton-unstable-(blue|green) 
Route: graviton
if this is not the expected behavior pls let me know.

[] decouple route :point_right: app-name = graviton-master, route = graviton
  as shown in the last action point this is now done. But I do have the feeling you meant s.th. else. Pls elaborate in case I did get you wrong.

**Comment by hairmare** [comment]
re unstable feature. The route should probably match the appname in that case. Part of the feature is also about not wanting devs to hog URLs with branches names since those should be left available for jenkins.

**Comment by lapistano** [comment]
so for now it is ok to merge? As I really want to finish this up now.

**Comment by lapistano** [comment]
updated https://github.com/libgraviton/deploy-scripts/pull/7#issuecomment-113526476

**Pull request merged**
