### PR TITLE
Fix slice recognition output

### PR DESCRIPTION
**Pull request by hairmare**
This has been bugging me for ages and is now getting adapted to say what it does.

### CODE REVIEW

**Comment by lugipfupf** [comment]
Wo muss ich mich denn da noch überall austragen? 

Lugi 

On 2016-07-11 11:10, Lucas Bickel wrote: 

> This has been bugging me for ages and is now getting adapted to say what it does. 
> -------------------------
> 
> YOU CAN VIEW, COMMENT ON, OR MERGE THIS PULL REQUEST ONLINE AT:
> 
> https://github.com/libgraviton/deploy-scripts/pull/25 [1] 
> 
> COMMIT SUMMARY
> 
> * Fix slice recognition output
> 
> FILE CHANGES
> 
> * M src/Services/CloudFoundry/DeploymentUtils.php [2] (2)
> * M src/Tests/Command/CloudFoundry/DeployCommandTest.php [3] (4)
> 
> PATCH LINKS:
> 
> * https://github.com/libgraviton/deploy-scripts/pull/25.patch [4]
> * https://github.com/libgraviton/deploy-scripts/pull/25.diff [5]
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [6].

 

Links:
------
[1] https://github.com/libgraviton/deploy-scripts/pull/25
[2] https://github.com/libgraviton/deploy-scripts/pull/25/files#diff-0
[3] https://github.com/libgraviton/deploy-scripts/pull/25/files#diff-1
[4] https://github.com/libgraviton/deploy-scripts/pull/25.patch
[5] https://github.com/libgraviton/deploy-scripts/pull/25.diff
[6]
https://github.com/notifications/unsubscribe/AFNw8df5K9fN1usST83ZnA3wZ-eOswCnks5qUgh4gaJpZM4JJKt_

**Comment by hairmare** [comment]
@lugipfupf Gute Frage :/ Einen "Unwatch" Knopf hast du oben nicht? Ich kann dich weder auf orga Ebene noch auf in der Liste der Follower noch sehen.

**Comment by lugipfupf** [comment]
Ja hab ich. Klick ich auch. Bekomme die notifications auch von immer neuen repos.
Lugi

**Comment by hairmare** [comment]
Das Ding ist, ich seh dich weder auf https://github.com/orgs/libgraviton/people noch irgendwo hier drunter: https://github.com/orgs/libgraviton/teams

Hast du da irgendwo noch nen leave bötten?

**Comment by lugipfupf** [comment]
Bin jetzt noch mal alle durch gegangen. War bei ca 18 noch eingetragen,
wo ich mich nie eingetragen hatte :-/ 

Bin gespannt, was passiert, wenn ein neues Repo erstellt wird. 

On 2016-07-11 13:29, Lucas Bickel wrote: 

> Das Ding ist, ich seh dich weder auf https://github.com/orgs/libgraviton/people [1] noch irgendwo hier drunter: https://github.com/orgs/libgraviton/teams [2] 
> 
> Hast du da irgendwo noch nen leave bötten? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4].

 

Links:
------
[1] https://github.com/orgs/libgraviton/people
[2] https://github.com/orgs/libgraviton/teams
[3]
https://github.com/libgraviton/deploy-scripts/pull/25#issuecomment-231709220
[4]
https://github.com/notifications/unsubscribe/AFNw8fB1aNqdkPgsrN9Xm7-ITwBVPL6Pks5qUikEgaJpZM4JJKt_

**Comment by hairmare** [comment]
Als Team-Member tuts dich automatisch rein. Ohne Membership solltest das nicht mehr passieren.

**Pull request merged**
